[2020/2/28 15:12:07][ERROR][uibot38385c2483da42.task][49] 运行发生错误，流程中止
错误信息如下：
uibot38385c2483da42.task 第49行： 尝试去连接一个null值 (字段 'AUTH1')
